# Generated by Django 4.1.1 on 2022-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_comm', '0002_resume_adres_alter_resume_phone_alter_resume_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('м', 'ж')], default='', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='adres',
            field=models.CharField(default='', max_length=50, verbose_name='adres'),
        ),
    ]
