# Generated by Django 4.1.1 on 2022-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_comm', '0004_resume_age_alter_resume_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='Нет опыта работы', verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='type_of_employment',
            field=models.CharField(choices=[('Полная', 'Полная'), ('Частичная', 'Частичная'), ('Удалённо', 'Удалённо')], default='', max_length=20, verbose_name='type_of_employment'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.CharField(max_length=3, verbose_name='age'),
        ),
    ]
