# Generated by Django 4.1.1 on 2022-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_comm', '0005_resume_experience_resume_type_of_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='confirm_skills',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default='', verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='', verbose_name='experience'),
        ),
    ]
