# Generated by Django 4.1.1 on 2022-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_comm', '0006_resume_confirm_skills_resume_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.CharField(default='', max_length=150, verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='confirm_skills',
            field=models.TextField(default='', max_length=50, verbose_name='confirm_skills'),
        ),
    ]
